export const LOAD_NEWS = "LOAD_NEWS";
export const NEWS_LOADED = "NEWS_LOADED";
export const SEARCH_NEWS = "SEARCH_NEWS";

export const NAVIGATION_PUSH = "NAVIGATION_PUSH";
export const NAVIGATION_POP = "NAVIGATION_POP";
export const NAVIGATION_TAB = "NAVIGATION_TAB";
export const NAVIGATION_OPEN_MODAL = "NAVIGATION_OPEN_MODAL";
export const NAVIGATION_CLOSE_MODAL = "NAVIGATION_CLOSE_MODAL";

export const BOOKMARK = "BOOKMARK";
export const LOADED_BOOKMARKS = "LOADED_BOOKMARKS";

export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";
